# =========================
# Project
# =========================
PROJECT_DIR=/opt/projects/ecommerce_dw
SCRIPT_DIR=/opt/projects/ecommerce_dw/scripts

# =========================
# MySQL
# =========================
MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_DB=ecommerce
MYSQL_USER=root
MYSQL_PASSWORD=123456

# =========================
# MySQL Data
# =========================
DATA_DIR=/opt/projects/ecommerce_dw/data
SCHEMA_FILE=/opt/projects/ecommerce_dw/mysql_schema/ecommerce_tables.sql

# =========================
# Hive Database
# =========================
HIVE_DB_ODS=ecommerce_ods
HIVE_DB_DWD=ecommerce_dwd
HIVE_DB_DWS=ecommerce_dws
HIVE_DB_ADS=ecommerce_ads

# =========================
# HDFS
# =========================
HDFS_FS=hdfs://dw-master:8020
ODS_HDFS_BASE=/warehouse/ods
DWD_HDFS_BASE=/warehouse/dwd

# =========================
# DataX
# =========================
DATAX_HOME=/opt/module/datax
JOB_TEMPLATE_DIR=/opt/projects/ecommerce_dw/datax_jobs/template
JOB_RENDER_DIR=/opt/projects/ecommerce_dw/datax_jobs/rendered

# =========================
# SQL Paths
# =========================
ODS_SQL=/opt/projects/ecommerce_dw/dw/ods/ods_tables.sql

DWD_TABLES_SQL=/opt/projects/ecommerce_dw/dw/dwd/dwd_tables.sql
DWD_BASE_SQL=/opt/projects/ecommerce_dw/dw/dwd/import_dwd_base.sql
DWD_ZIP_SQL=/opt/projects/ecommerce_dw/dw/dwd/import_dwd_zip.sql
DWD_WIDE_SQL=/opt/projects/ecommerce_dw/dw/dwd/import_dwd_wide.sql

DWS_TABLES_SQL=/opt/projects/ecommerce_dw/dw/dws/dws_tables.sql
DWS_IMPORT_SQL=/opt/projects/ecommerce_dw/dw/dws/import_dws.sql

ADS_TABLES_SQL=/opt/projects/ecommerce_dw/dw/ads/ads_tables.sql
ADS_IMPORT_SQL=/opt/projects/ecommerce_dw/dw/ads/import_ads.sql